stages:
  tiler:
    cmd: C:\Python37\python.exe ..\..\tools\Tiler\tiler.py
    wdir: Standalone_GCBM\layers\tiled
    deps:
    - ..\..\tools\Tiler\tiler.py
    - ..\raw\environment
    - ..\raw\inventory
    outs:
    - ..\..\logs\tiler_log.txt
  recliner2gcbm_x64:
    cmd: tools\Recliner2GCBM-x64\Recliner2GCBM.exe -c input_database\recliner2gcbm_config.json >> logs\recliner_log.txt
    wdir: Standalone_GCBM
    deps:
    - logs\tiler_log.txt
    - tools\recliner2gcbm-x64\recliner2gcbm.exe
    - input_database\recliner2gcbm_config.json
    - input_database\ArchiveIndex_Beta_Install.mdb
    - input_database\Growth_Curves.csv
    - input_database\gcbm_input.db
    outs:
    - logs\recliner_log.txt
  update_gcbm_configuration:
    cmd: update_gcbm_configuration.bat
    wdir: Standalone_GCBM\gcbm_project
    deps:
    - ..\logs\recliner_log.txt
    - update_gcbm_configuration.bat
    - ..\tools\tiler\update_gcbm_config.py
    - templates
    - ..\layers\tiled
    - ..\input_database\gcbm_input.db
    outs:
    - ..\logs\update_gcbm_config.log
  run_gcbm:
    cmd: run_gcbm.bat
    wdir: Standalone_GCBM\gcbm_project
    deps:
    - ..\logs\update_gcbm_config.log
    - run_gcbm.bat
    - ..\tools\GCBM\moja.cli.exe
    - gcbm_config.cfg
    - provider_config.json
    - ..\input_database\gcbm_input.db
    - output\gcbm_output.db
    outs:
    - ..\logs\Moja_Debug.log
  create_tiffs:
    cmd: create_tiffs.bat
    wdir: Standalone_GCBM\tools\CompileGCBMSpatialOutput
    deps:
    - ..\..\logs\Moja_Debug.log
    - create_tiffs.bat
    - create_tiffs.py
    - ..\..\gcbm_project\output
    outs:
    - ..\..\logs\create_tiffs.log
    - ..\..\processed_output\spatial
  compile_results:
    cmd: C:\Python37\python.exe compileresults.py sqlite:///../../gcbm_project/output/gcbm_output.db --output_db sqlite:///../../processed_output/compiled_gcbm_output.db >> ..\..\logs\compile_results.log
    wdir: Standalone_GCBM\tools\CompileGCBMResults
    deps:
    - ..\..\logs\create_tiffs.log
    - compileGCBMResults.bat
    - compileresults.py
    - ..\..\gcbm_project\output\gcbm_output.db
    - compileresults.json
    - ..\..\processed_output\compiled_gcbm_output.db
    outs:
    - ..\..\logs\compile_results.log