stages:
  tiler:
    cmd: python ../../tools/Tiler/tiler.py
    wdir: Standalone_GCBM/layers/tiled
    deps:
    - ../../tools/Tiler/tiler.py
    - ../raw/environment
    - ../raw/inventory
    outs:
    - ../../logs/tiler_log.txt
  recliner2gcbm_x64:
    cmd: tools\Recliner2GCBM-x64\Recliner2GCBM.exe -c input_database\recliner2gcbm_config.json >> logs\recliner_log.txt
    wdir: Standalone_GCBM
    deps:
    - logs\tiler_log.txt
    - tools\recliner2gcbm-x64\recliner2gcbm.exe
    - input_database\recliner2gcbm_config.json
    - input_database\ArchiveIndex_Beta_Install.mdb
    - input_database\Growth_Curves.csv
    - input_database\gcbm_input.db
    outs:
    - logs\recliner_log.txt
  update_gcbm_configuration:
    cmd: update_gcbm_configuration.bat
    wdir: Standalone_GCBM\gcbm_project
    deps:
    - ..\logs\recliner_log.txt
    - update_gcbm_configuration.bat
    - ..\tools\tiler\update_gcbm_config.py
    - templates
    - ..\layers\tiled
    - ..\input_database\gcbm_input.db
    outs:
    - ..\logs\update_gcbm_config.log
  run_gcbm:
    cmd: run_gcbm.bat
    wdir: Standalone_GCBM\gcbm_project
    deps:
    - ..\logs\update_gcbm_config.log
    - run_gcbm.bat
    - ..\tools\GCBM\moja.cli.exe
    - gcbm_config.cfg
    - localdomain.json
    - pools_cbm.json
    - modules_cbm.json
    - modules_output.json
    - spinup.json
    - variables.json
    - internal_variables.json
    - provider_config.json
    - ..\layers\tiled\LifeZone_moja.tiff
    - ..\layers\tiled\mean_annual_temperature_moja.tiff
    - ..\input_database\gcbm_input.db
    - output\gcbm_output.db
    outs:
    - ..\logs\Moja_Debug.log
  create_tiffs:
    cmd: create_tiffs.bat
    wdir: Standalone_GCBM\tools\CompileGCBMSpatialOutput
    deps:
    - ..\..\logs\Moja_Debug.log
    - create_tiffs.bat
    - create_tiffs.py
    - ..\..\gcbm_project\output
    outs:
    - ..\..\logs\create_tiffs.log
    - ..\..\processed_output\spatial
  compile_results:
    cmd: compileGCBMResults.bat
    wdir: Standalone_GCBM\tools\CompileGCBMResults
    deps:
    - ..\..\gcbm_project\output\gcbm_output.db
    - ..\..\logs\create_tiffs.log
    - ..\..\processed_output\compiled_gcbm_output.db
    - compileGCBMResults.bat
    - compileresults.json
    - compileresults.py
    outs:
    - ..\..\logs\compile_results.log
