name: gcbm-Carpathians-CML
on: 
  push:
    paths:
      - Standalone_GCBM/input_database/gcbm_input.db
      - test-windows-cml-complete.txt
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          pip install installation\GDAL-2.4.1-cp37-cp37m-win_amd64.whl
          del /q "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\osgeo\gdalplugins\*.*"
          
          pip install -r installation\requirements-py37.txt

          pip freeze > result.txt

      - name: dvc repro - compile_results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          dvc repro -s compile_results 

      - name: Installations and renv restore
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          pip install pandas
          cd Postprocessing
          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

      - name: dvc repro - postprocessing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s postprocessing

      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics diff --show-md > report.md
          echo "## Figures created" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md
          