name: gcbm-Carpathians-ubuntu-CML
on: push

jobs:
  run-on-container:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies           
      run: |           
        sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update            
        sudo apt-get install gdal-bin           
        sudo apt-get install libgdal-dev            
        export CPLUS_INCLUDE_PATH=/usr/include/gdal            
        export C_INCLUDE_PATH=/usr/include/gdal           
        pip install wheel            
        pip install numpy           
        sudo pip3 install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal"
                
          