name: gcbm-Carpathians-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v2
      - uses: iterative/setup-dvc@v2
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Intall mojadata through pip
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          pip install mojadata

          pip freeze > report.md
          cml comment create --publish --pr=false report.md

          