name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Check python path
        run: python -c 'import sys; print(sys.executable)'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          python --version > report.txt
          
          set PYTHONHOME=C:\hostedtoolcache\windows\Python\3.7.9\x64
          set PATH_PYTHON=%PYTHONHOME%   

          pip install installation/GDAL-2.4.1-cp37-cp37m-win_amd64.whl      
          del /q "${PATH_PYTHON}\lib\site-packages\osgeo\gdalplugins\*.*"

          pip install installation/mojadata-3.4.3-py3-none-any.whl

          pip freeze > result.txt

          type report.txt result.txt > report.md
          cml comment create --publish --pr=false report.md