name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Check python path
        run: |
          python -c 'import sys; print(sys.executable)'
          python -c 'import os; print(os.path.expanduser('~'))'