name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          python-version: 3.7.9
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          python --version > report.md

          cml comment create --publish --pr=false report.md
