name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          python --version > report.md
          dvc pull -r install_tools
          pip install installation/mojadata-3.4.3-py3-none-any.whl
          pip freeze > versions.txt
          cat versions.txt >> report.md

          cml comment create --publish --pr=false report.md
