name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Check python path
        run: |
          python -c 'import sys; print(sys.executable)'
          PATH_PYTHON=$(python -c 'import sys; print(sys.executable)')
          SETUP_PYTHON=$('${{ steps.setup-python.outputs.python-path }}' -c 'import sys; print(sys.executable)')
          if [ "${SETUP_PYTHON}" != "${PATH_PYTHON}" ]; then
            echo "Executable mismatch. python in PATH is ${PATH_PYTHON}; python-path (${{ steps.setup-python.outputs.python-path }}) is ${SETUP_PYTHON}"
            exit 1