name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          python --version > report.md
          pip install -r installation/requirements.txt
          pip install installation/*.whl

          dvc repro -s tiler > result.txt

          cat result.txt >> report.md
          cml comment create --publish --pr=false report.md
