name: gcbm-Carpathains-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          python --version > report.md
          sudo apt install libgdal-dev
          pip install -r requirements.txt
          rm -r python\lib\site-packages\osgeo\gdalplugins\*.*
          cat pip freeze >> report.md

          cml comment create --publish --pr=false report.md
