name: gcbm-Carpathians-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          pip install installation\GDAL-2.4.1-cp37-cp37m-win_amd64.whl
          pip install installation\mojadata-3.4.3-py3-none-any.whl
          pip install -r installation\requirements-py37.txt

          pip freeze > result.txt
          type result.txt

      - name: dvc repro - tiler stage
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          dvc repro -s tiler > report.md
          dvc dag > dag.md

          type report.md dag.md > report.md
          cml comment create --publish --pr=false report.md
          