name: gcbm-Carpathians-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          python --version > report.txt
          
          pip install installation\GDAL-2.4.1-cp37-cp37m-win_amd64.whl
          pip install installation\mojadata-3.4.3-py3-none-any.whl
          pip install -r installation\requirements-py37.txt

          pip freeze > result.txt

          result.txt