name: gcbm-Carpathians-ubuntu-CML
on: push
jobs:
  run-on-container:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/checkout@v3  