name: gcbm-Carpathians-ubuntu-CML
on: push
jobs:
  run-on-container:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - uses: actions/checkout@v3
      - uses: iterative/setup-dvc@v1
          
      - name: Compile Results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s compile_results
      
      - uses: actions/upload-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/compiled_gcbm_output.db
  
  run-on-vmhost:
    runs-on: [ubuntu-latest]
    needs: run-on-container
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: compiled-gcbm-output
          path: Standalone_GCBM/processed_output/

      - name: dvc repro - postprocessing
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s postprocessing
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Figures created" > report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md
        
          