name: gcbm-Carpathians-ubuntu-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r installation/requirements.txt

          sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
          sudo apt-get update
          sudo apt-get install gdal-bin
          sudo apt-get install libgdal-dev
          export CPLUS_INCLUDE_PATH=/usr/include/gdal
          export C_INCLUDE_PATH=/usr/include/gdal
          pip install GDAL

          pip freeze > result.txt
          cat result.txt
          
      - name: dvc repro - run_gcbm
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -l dvc repro -s run_gcbm