name: gcbm-Carpathians-ubuntu-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml ci
          pip install -r installation/requirements.txt

          pip freeze > result.txt
          cat result.txt
          
      - name: dvc repro - run_gcbm
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s run_gcbm 
          echo "1. Ran run_gcbm stage" > report.md

          cat Standalone_GCBM/logs/Moja_Debug.log

      - name: dvc repro - compile_results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s compile_results 
          echo "2. Ran compile_results stage" >> report.md

          cat Standalone_GCBM/logs/compile_results.log

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
      - uses: r-lib/actions/setup-renv@v2
      
      - name: Renv and run postprocessing code
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          cd Postprocessing
          Rscript -e "getwd()"

          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

          Rscript Summarize_DOM_Stocks.R
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Figures created" >> report.md
          echo "![](/Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png)" >> report.md 
          echo "![](/Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png)" >> report.md
          echo "![](/Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png)" >> report.md
          echo "![](/Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png)" >> report.md
          echo "![](/Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png)" >> report.md
          cml comment create --pr=false report.md
          