name: test-R-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2

      - name: Check R version and try restoring renv
        run: | 
          Rscript -e 'renv::restore()'