name: test-R-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'

      - name: Get wd
        run: | 
          Rscript -e "getwd()"
      
      - name: renv status and run postprocessing code
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          Rscript -e "setwd('Postprocessing')"
          Rscript -e "getwd()"
