name: test-R-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'

      - name: Renv and run postprocessing code
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          cd Postprocessing
          Rscript -e "getwd()"

          Rscript -e "renv::activate()"
          Rscript -e "renv::restore(lockfile = 'renv.lock')"

          Rscript Summarize_DOM_Stocks.R
        
      - name: Display plots for DOM stocks
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Figures created" > report.md
          cml_publish Postprocessing/Figures/Carpathians_Sensitivity_BorealWet.png --md >> report.md
          cml_publish Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateMoist.png --md >> report.md
          cml_publish Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateSteppe.png --md >> report.md
          cml_publish Postprocessing/Figures/Carpathians_Sensitivity_CoolTemperateWet.png --md >> report.md
          cml_publish Postprocessing/Figures/Carpathians_Sensitivity_PolarRainTundra.png --md >> report.md
          cml comment create --publish --pr=false report.md