name: test-R-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check R version and try restoring renv
        run: | 
          R --version 

          Rscript -e 'install.packages("renv")'