name: test-container-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3

      - name: Check current directory
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
        
      - name: Initial run of gcbm 
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Standalone_GCBM/gcbm_project

          /opt/gcbm/moja.cli --config_file gcbm_config.cfg --config_provider provider_config.json