name: test-R-CML
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: 
      image: ghcr.io/moja-global/rest_api_gcbm:master
      ports:
        - "8080:8080"
    steps:      
      - name: Initial run of dvc repro - run gcbm 
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro -s run_gcbm