name: gcbm-Carpathians-CML
on: push
jobs:
  run:
    runs-on: [windows-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.9'

      - name: Required Installations
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          installation\AccessDatabaseEngine_x64.exe /passive

          pip install installation\GDAL-2.4.1-cp37-cp37m-win_amd64.whl
          del /q "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\osgeo\gdalplugins\*.*"
          
          pip install -r installation\requirements-py37.txt

      - name: dvc repro - create_tiffs
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: | 
          dvc repro -s create_tiffs 

          type Standalone_GCBM\logs\create_tiffs.log
          echo ran create_tiffs stage >> report.md

      - name: dvc repro - compile_results
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: cmd
        run: |
          dvc repro -s compile_results 

          Standalone_GCBM\logs\compile_results.log
          echo ran compile_results stage >> report.md

          cml comment create --publish --pr=false report.md
          